-- local M = {}
--
-- function M.setup()
--   ------------------------------------------------------------------
--   -- Treesitter Context
--   ------------------------------------------------------------------
--
--   vim.api.nvim_set_hl(0, "TreesitterContext", {
--     bg = "#1F1F28",
--   })
--
--   vim.api.nvim_set_hl(0, "TreesitterContextLineNumber", {
--     fg = "#727169",
--     bg = "#1F1F28",
--   })
--
--   vim.api.nvim_set_hl(0, "TreesitterContextSeparator", {
--     fg = "#54546D",
--   })
-- end
--
-- ----------------------------------------------------------
-- -- Neo-tree
-- ----------------------------------------------------------
--
-- vim.api.nvim_set_hl(0, "NeoTreeNormal", {
--   bg = "#1F1F28",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeNormalNC", {
--   bg = "#1F1F28",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeEndOfBuffer", {
--   bg = "#1F1F28",
--   fg = "#1F1F28",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeWinSeparator", {
--   fg = "#2A2A37",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeIndentMarker", {
--   fg = "#2A2A37",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeRootName", {
--   fg = "#7E9CD8",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeGitModified", {
--   fg = "#DCA561",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeGitAdded", {
--   fg = "#98BB6C",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeGitDeleted", {
--   fg = "#E46876",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeFileNameOpened", {
--   fg = "#7FB4CA",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeDirectoryName", {
--   fg = "#7E9CD8",
-- })
--
-- vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", {
--   fg = "#7E9CD8",
-- })
--
-- ----------------------------------------------------------
-- -- Flash
-- ----------------------------------------------------------
--
-- vim.api.nvim_set_hl(0, "FlashLabel", {
--   fg = "#1F1F28",
--   bg = "#FF9E3B",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "FlashMatch", {
--   fg = "#7E9CD8",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "FlashCurrent", {
--   fg = "#98BB6C",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "FlashBackdrop", {
--   fg = "#54546D",
-- })
--
-- ----------------------------------------------------------
-- -- WhichKey
-- ----------------------------------------------------------
--
-- vim.api.nvim_set_hl(0, "WhichKey", {
--   fg = "#7E9CD8",
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeyGroup", {
--   fg = "#98BB6C",
--   bold = true,
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeyDesc", {
--   fg = "#DCD7BA",
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeySeparator", {
--   fg = "#727169",
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeyBorder", {
--   fg = "#54546D",
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeyNormal", {
--   bg = "#1F1F28",
-- })
--
-- vim.api.nvim_set_hl(0, "WhichKeyTitle", {
--   fg = "#FF9E3B",
--   bold = true,
-- })
--
-- return M
