return {
  -- "nvimdev/dashboard-nvim",
  --
  -- event = "VimEnter",
  --
  -- opts = function()
  --   local logo = {
  --     "",
  --     "",
  --     "",
  --     "",
  --     "",
  --     "  ███╗   ██╗██╗   ██╗██╗███╗   ███╗",
  --     "  ████╗  ██║██║   ██║██║████╗ ████║",
  --     "  ██╔██╗ ██║██║   ██║██║██╔████╔██║",
  --     "  ██║╚██╗██║╚██╗ ██╔╝██║██║╚██╔╝██║",
  --     "  ██║ ╚████║ ╚████╔╝ ██║██║ ╚═╝ ██║",
  --     "  ╚═╝  ╚═══╝  ╚═══╝  ╚═╝╚═╝     ╚═╝",
  --     "",
  --     "",
  --     "        ⚡ LazyVim + AI IDE",
  --     "",
  --     "",
  --   }
  --
  --   return {
  --     theme = "doom",
  --
  --     config = {
  --
  --       header = logo,
  --
  --       center = {
  --
  --         {
  --           icon = " 󰈞  ",
  --           desc = " Find File",
  --           key = "f",
  --           action = "Telescope find_files",
  --         },
  --
  --         {
  --           icon = " 󰊄  ",
  --           desc = " Recent Files",
  --           key = "r",
  --           action = "Telescope oldfiles",
  --         },
  --
  --         {
  --           icon = " 󰒲  ",
  --           desc = " Lazy",
  --           key = "l",
  --           action = "Lazy",
  --         },
  --
  --         {
  --           icon = " 󰈢  ",
  --           desc = " Projects",
  --           key = "p",
  --           action = "Telescope projects",
  --         },
  --
  --         {
  --           icon = " 󰈬  ",
  --           desc = " New File",
  --           key = "n",
  --           action = "ene | startinsert",
  --         },
  --       },
  --
  --       footer = function()
  --         local stats = require("lazy").stats()
  --         return {
  --           "⚡ Loaded " .. stats.count .. " plugins in " .. stats.startuptime .. "ms",
  --         }
  --       end,
  --     },
  --   }
  -- end,
}
